sudo: required
services:
  - docker
language: node_js
env:
  global:
    - TEST_INTEGRATION_KONG_HOST="127.0.0.1:8001"
  matrix:
    - KONG_VERSION=latest
    - KONG_VERSION=0.9
node_js:
    - "stable"
    - "4"
    - "6"
before_install:
    -  docker run -d --name kong-database -e "POSTGRES_USER=kong" -e "POSTGRES_DB=kong"  postgres:9.4
    -  sleep 5
    -  docker run -d --name kong --link kong-database:kong-database -e "KONG_DATABASE=postgres" -e "KONG_PG_HOST=kong-database" -p 127.0.0.1:8001:8001 -p 127.0.0.1:8000:8000 kong:$KONG_VERSION
    -  sleep 5
    -  curl localhost:8001
